In [214]:
import pandas as pd
df=pd.read_csv('hw5-trainingset-zr2209.csv', sep=',',header=None)
df_test = pd.read_csv('hw5-testset-zr2209.csv', sep=',',header=None)

/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (2,15,16,17,23,33,43,44,45,50,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,78,80,82,84,86,88,90,92,94,96,98,100,106,108,109,111,122,124,126,129,130,141,143,144,146,147,149,150,160,161,162,172,183,203,205,207,208,211,212,217,219,221,223,234,235,236,250,251,252,253,255,256,257,258,262,265,272,274,275,277,279,280,282,283,374,375,376,377,378) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (2,15,16,17,23,33,43,44,45,50,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,78,80,82,84,86,88,90,92,94,96,98,100,106,108,109,111,122,124,126,129,130,141,143,144,146,147,149,150,160,161,162,183,203,205,207,208,211,212,217,219,221,223,234,235,236,250,251,252,253,255,256,257,258,260,262,265,268,272,274,275,277,280,282,283,374,375,376,377,378) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [165]:
df

,0,1,2,3,4,5,6,7,8,9,...,370,371,372,373,374,375,376,377,378,379
0,cntryid,cntryid_e,age_r,gender_r,computerexperience,nativespeaker,edlevel3,monthlyincpr,yearlyincpr,lng_home,...,v85,v50,v89,v127,v239,v224,v71,v105,row,uni
1,United States,United States,NaN,Male,Yes,Yes,High,NaN,NaN,999,...,Agree,Agree,NaN,NaN,9999,9996,9999,9996,29198,zr2209
2,United Kingdom,England (UK),58,Male,Yes,No,High,90 or more,90 or more,srp,...,Agree,Disagree,NaN,NaN,2144,9996,7110,9996,59475,zr2209
3,Japan,Japan,44,Female,Yes,Yes,High,50 to less than 75,50 to less than 75,jpn,...,Neither agree nor disagree,Disagree,NaN,NaN,2265,9996,8510,9996,39400,zr2209
4,Denmark,Denmark,49,Male,Yes,Yes,Medium,50 to less than 75,50 to less than 75,dan,...,Agree,Agree,NaN,NaN,3116,9996,210,9996,190425,zr2209
5,Germany,Germany,NaN,Male,Yes,No,Medium,25 to less than 50,25 to less than 50,999,...,Agree,Agree,NaN,NaN,9999,9996,9999,9996,19494,zr2209
6,Slovak Republic,Slovak Republic,31,Male,Yes,Yes,Medium,10 to less than 25,10 to less than 25,slk,...,Agree,Disagree,NaN,NaN,7231,9996,4520,9996,539,zr2209
7,Chile,Chile,27,Male,Yes,Yes,High,NaN,NaN,spa,...,Neither agree nor disagree,Neither agree nor disagree,NaN,NaN,9996,2512,9996,6201,102185,zr2209
8,Belgium,Flanders (Belgium),36,Male,Yes,Yes,High,90 or more,90 or more,nld,...,Agree,Agree,NaN,NaN,3116,9996,NaN,9996,180148,zr2209
9,Russian Federation,Russian Federation,34,Male,Yes,Yes,High,50 to less than 75,50 to less than 75,999,...,Agree,Strongly agree,NaN,NaN,1222,9996,731,9996,71612,zr2209
10,Germany,Germany,NaN,Female,Yes,Yes,Medium,NaN,NaN,999,...,Neither agree nor disagree,Neither agree nor disagree,NaN,NaN,9996,9999,9996,9999,194844,zr2209
11,Finland,Finland,30,Male,Yes,Yes,High,Less than 10,Less than 10,fin,...,Strongly agree,Strongly agree,NaN,NaN,9999,9996,9999,9996,195328,zr2209
12,United States,United States,NaN,Female,Yes,Yes,Medium,75 to less than 90,75 to less than 90,999,...,Agree,Agree,NaN,NaN,9999,9996,9999,9996,12272,zr2209
13,United States,United States,NaN,Female,Yes,Yes,Medium,25 to less than 50,25 to less than 50,999,...,Strongly agree,Strongly agree,NaN,NaN,9999,9996,9999,9996,99479,zr2209
14,Czech Republic,Czech Republic,37,Female,Yes,Yes,Medium,Less than 10,10 to less than 25,ces,...,Agree,Agree,NaN,NaN,5249,9996,7110,9996,79644,zr2209
15,Denmark,Denmark,52,Male,Yes,Yes,High,90 or more,90 or more,dan,...,Disagree,Disagree,NaN,NaN,7115,9996,4330,9996,23136,zr2209
16,Germany,Germany,NaN,Male,Yes,Yes,High,90 or more,90 or more,999,...,Agree,Neither agree nor disagree,NaN,NaN,9999,9996,9999,9996,13478,zr2209
17,United Kingdom,England (UK),30,Male,Yes,Yes,Medium,75 to less than 90,75 to less than 90,eng,...,Agree,Agree,NaN,NaN,1221,9996,7020,9996,134185,zr2209
18,Chile,Chile,50,Male,Yes,Yes,High,90 or more,90 or more,spa,...,Strongly disagree,Disagree,NaN,NaN,2132,9996,8413,9996,34249,zr2209
19,France,France,43,Female,Yes,No,Medium,25 to less than 50,50 to less than 75,spa,...,Strongly agree,Strongly agree,NaN,NaN,3341,9996,8890,9996,172711,zr2209
20,Russian Federation,Russian Federation,49,Female,Yes,Yes,High,10 to less than 25,10 to less than 25,999,...,Agree,Agree,NaN,NaN,233,9996,8521,9996,84074,zr2209
21,France,France,45,Male,Yes,Yes,High,75 to less than 90,75 to less than 90,fra,...,Agree,Agree,NaN,NaN,2433,9996,3320,9996,134501,zr2209
22,Japan,Japan,37,Female,Yes,Yes,High,25 to less than 50,25 to less than 50,jpn,...,Agree,Neither agree nor disagree,NaN,NaN,4110,9996,2100,9996,8018,zr2209
23,Japan,Japan,56,Male,Yes,Yes,High,90 or more,90 or more,jpn,...,Neither agree nor disagree,Neither agree nor disagree,NaN,NaN,3341,9996,8413,9996,172226,zr2209
24,Russian Federation,Russian Federation,20,Male,Yes,Yes,Medium,NaN,NaN,999,...,Neither agree nor disagree,Neither agree nor disagree,NaN,NaN,2513,9996,6201,9996,180608,zr2209
25,Turkey,Turkey,20,Female,Yes,Yes,Medium,NaN,NaN,999,...,NaN,NaN,NaN,NaN,9996,5223,9996,4771,56144,zr2209
26,Poland,Poland,25,Male,Yes,Yes,High,NaN,NaN,pol,...,Agree,Agree,NaN,NaN,9996,5223,9996,4630,153279,zr2209
27,United States,United States,NaN,Male,Yes,Yes,Medium,NaN,NaN,999,...,Agree,Agree,NaN,NaN,9999,9996,9999,9996,185355,zr2209
28,Germany,Germany,NaN,Male,Yes,Yes,Medium,10 to less than 25,10 to less than 25,999,...,Neither agree nor disagree,Neither agree nor disagree,NaN,NaN,9999,9996,9999,9996,63312,zr2209
29,Russian Federation,Russian Federation,48,Female,Yes,Yes,High,25 to less than 50,25 to less than 50,999,...,Neither agree nor disagree,Strongly agree,NaN,NaN,2411,9996,692,9996,184964,zr2209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19971,France,France,59,Male,Yes,Yes,Medium,90 or more,90 or more,fra,...,Strongly agree,Strongly agree,NaN,NaN,1321,9996,2592,9996,127096,zr2209
19972,Canada,Canada (French),NaN,Male,Yes,Yes,High,90 or more,75 to less than 90,999,...,Strongly agree,Strongly agree,NaN,NaN,9999,9996,9999,9999,104131,zr2209
19973,Germany,Germany,NaN,Male,Yes,Yes,Medium,25 to less than 50,25 to less than 50,999,...,Disagree,Strongly agree,NaN,NaN,9999,9996,9999,9996,62850,zr2209
19974,Chile,Chile,24,Male,Yes,Yes,Medium,NaN,NaN,spa,...,Agree,Strongly agree,NaN,NaN,5222,9996,4771,9996,189563,zr2209
19975,France,France,41,Female,Yes,Yes,Medium,50 to less than 75,50 to less than 75,fra,...,Agree,Strongly agree,NaN,NaN,3313,9996,2219,9996,110750,zr2209
19976,Japan,Japan,48,Male,Yes,Yes,High,90 or more,90 or more,jpn,...,Disagree,Agree,NaN,NaN,1221,9996,4330,9996,115597,zr2209
19977,Spain,Spain,36,Male,Yes,Yes,Medium,50 to less than 75,50 to less than 75,spa,...,Strongly agree,Strongly agree,NaN,NaN,5221,9996,9999,9996,81640,zr2209
19978,Canada,Canada (English),NaN,Female,Yes,Yes,High,90 or more,90 or more,999,...,Disagree,Neither agree nor disagree,NaN,NaN,9999,9996,9999,9999,30526,zr2209
19979,United States,United States,NaN,Female,Yes,Yes,Medium,10 to less than 25,25 to less than 50,999,...,Strongly agree,Strongly agree,NaN,NaN,9999,9996,9999,9996,110312,zr2209
19980,Russian Federation,Russian Federation,49,Female,Yes,No,High,75 to less than 90,75 to less than 90,999,...,Agree,Agree,NaN,NaN,1346,9996,6419,9996,32465,zr2209
19981,France,France,28,Female,Yes,Yes,Medium,NaN,NaN,fra,...,Strongly agree,Strongly agree,NaN,NaN,9996,3322,9996,4771,44084,zr2209
19982,United States,United States,NaN,Male,Yes,Yes,Medium,NaN,NaN,999,...,Agree,Agree,NaN,NaN,9999,9996,9999,9996,185355,zr2209
19983,Turkey,Turkey,32,Male,Yes,Yes,Low,25 to less than 50,25 to less than 50,999,...,NaN,NaN,NaN,NaN,5223,9996,4630,8411,172329,zr2209
19984,Chile,Chile,35,Male,Yes,Yes,High,25 to less than 50,NaN,spa,...,Strongly agree,Strongly agree,NaN,NaN,3339,9996,9000,9996,67178,zr2209
19985,France,France,31,Female,Yes,Yes,High,25 to less than 50,25 to less than 50,fra,...,Agree,Agree,NaN,NaN,5223,9996,8292,9996,81895,zr2209
19986,Germany,Germany,NaN,Male,Yes,Yes,High,10 to less than 25,10 to less than 25,999,...,Agree,Strongly agree,NaN,NaN,9999,9996,9999,9996,168921,zr2209
19987,United Kingdom,England (UK),51,Female,Yes,Yes,High,50 to less than 75,50 to less than 75,eng,...,Strongly agree,Strongly agree,NaN,NaN,422,9996,7710,9996,63642,zr2209
19988,Turkey,Turkey,31,Female,Yes,Yes,High,NaN,NaN,999,...,NaN,NaN,NaN,NaN,9996,4132,9996,6920,18749,zr2209
19989,Germany,Germany,NaN,Male,Yes,No,Medium,50 to less than 75,50 to less than 75,999,...,Agree,Strongly agree,NaN,NaN,9999,9996,9999,9996,113554,zr2209
19990,Germany,Germany,NaN,Male,Yes,Yes,High,Less than 10,Less than 10,999,...,Disagree,Disagree,NaN,NaN,9999,9996,9999,9996,48779,zr2209
19991,Poland,Poland,53,Male,Yes,Yes,Medium,50 to less than 75,50 to less than 75,pol,...,Agree,Agree,NaN,NaN,5243,9996,4719,9996,81714,zr2209
19992,Chile,Chile,34,Male,Yes,Yes,High,Less than 10,NaN,spa,...,Strongly agree,Strongly agree,NaN,NaN,7111,9996,4100,9996,8177,zr2209
19993,Poland,Poland,45,Female,Yes,Yes,High,25 to less than 50,25 to less than 50,pol,...,Strongly agree,Strongly agree,NaN,NaN,3313,9996,6920,9996,91708,zr2209
19994,Germany,Germany,NaN,Male,Yes,Yes,High,75 to less than 90,75 to less than 90,999,...,Neither agree nor disagree,Neither agree nor disagree,NaN,NaN,9999,9996,9999,9996,37306,zr2209
19995,Korea,Korea,56,Male,Yes,Yes,Medium,90 or more,90 or more,kor,...,Agree,Disagree,NaN,NaN,3353,9996,8422,9996,67815,zr2209
19996,Turkey,Turkey,45,Male,Yes,Yes,High,75 to less than 90,75 to less than 90,999,...,NaN,NaN,NaN,NaN,4211,9996,6411,9996,73168,zr2209
19997,Germany,Germany,NaN,Male,Yes,Yes,Medium,NaN,NaN,999,...,Neither agree nor disagree,Agree,NaN,NaN,9996,9999,9996,9999,143397,zr2209
19998,United Kingdom,England (UK),48,Male,Yes,Yes,High,90 or more,90 or more,eng,...,Disagree,Agree,NaN,NaN,3323,9996,8411,9996,78714,zr2209
19999,Germany,Germany,NaN,Male,Yes,Yes,High,75 to less than 90,75 to less than 90,999,...,Strongly agree,Agree,NaN,NaN,9999,9996,9999,9996,94816,zr2209
20000,Netherlands,Netherlands,48,Male,Yes,Yes,Medium,75 to less than 90,75 to less than 90,nld,...,Agree,Disagree,NaN,NaN,3322,9996,2822,9996,62678,zr2209

In [166]:
df_test

,0,1,2,3,4,5,6,7,8,9,...,370,371,372,373,374,375,376,377,378,379
0,cntryid,cntryid_e,age_r,gender_r,computerexperience,nativespeaker,edlevel3,monthlyincpr,yearlyincpr,lng_home,...,v85,v50,v89,v127,v239,v224,v71,v105,row,uni
1,Turkey,Turkey,22,Female,Yes,Yes,Low,NaN,NaN,999,...,NaN,NaN,NaN,NaN,9996,9996,9996,9996,188703,zr2209
2,France,France,38,Male,Yes,Yes,Medium,25 to less than 50,50 to less than 75,fra,...,Strongly agree,Strongly agree,NaN,NaN,3123,9996,4312,9996,21130,zr2209
3,Turkey,Turkey,19,Male,Yes,Yes,Medium,NaN,NaN,999,...,NaN,NaN,NaN,NaN,9996,9996,9996,9996,110731,zr2209
4,Japan,Japan,42,Female,Yes,Yes,Medium,Less than 10,Less than 10,jpn,...,Strongly disagree,Agree,NaN,NaN,4212,9996,9200,9996,39944,zr2209
5,Japan,Japan,27,Male,Yes,Yes,High,25 to less than 50,25 to less than 50,jpn,...,Strongly agree,Agree,NaN,NaN,3339,9996,6312,9996,15584,zr2209
6,Japan,Japan,61,Male,Yes,Yes,High,90 or more,90 or more,jpn,...,Agree,Disagree,NaN,NaN,3134,9996,1920,9996,8986,zr2209
7,United Kingdom,England (UK),55,Female,Yes,Yes,High,Less than 10,Less than 10,eng,...,Disagree,Disagree,NaN,NaN,431,9996,8620,9996,188269,zr2209
8,Israel,Israel,19,Female,Yes,Yes,Medium,Less than 10,Less than 10,ara,...,Disagree,Strongly agree,NaN,NaN,5223,9996,4721,9996,127184,zr2209
9,Greece,Greece,62,Male,Yes,Yes,Medium,NaN,NaN,ell,...,Strongly agree,Strongly agree,NaN,NaN,9996,9996,9996,9996,103553,zr2209
10,Poland,Poland,30,Female,Yes,Yes,High,50 to less than 75,50 to less than 75,pol,...,Agree,Agree,NaN,NaN,2310,9996,8530,9996,95830,zr2209
11,Belgium,Flanders (Belgium),56,Male,Yes,Yes,Medium,50 to less than 75,50 to less than 75,nld,...,Neither agree nor disagree,Disagree,NaN,NaN,9622,9996,5310,9996,175973,zr2209
12,Turkey,Turkey,24,Male,Yes,Yes,High,Less than 10,NaN,999,...,NaN,NaN,NaN,NaN,3431,9996,7420,9996,36639,zr2209
13,Poland,Poland,37,Male,Yes,Yes,Medium,10 to less than 25,10 to less than 25,pol,...,Agree,Agree,NaN,NaN,8131,9996,3290,9996,130932,zr2209
14,Turkey,Turkey,32,Female,Yes,Yes,Low,NaN,NaN,999,...,NaN,NaN,NaN,NaN,9996,9996,9996,9996,31490,zr2209
15,Germany,Germany,NaN,Female,Yes,Yes,Low,NaN,NaN,999,...,Agree,Neither agree nor disagree,NaN,NaN,9996,9996,9996,9996,31525,zr2209
16,Italy,Italy,21,Male,Yes,Yes,Medium,NaN,NaN,999,...,Agree,Agree,NaN,NaN,9996,5131,9996,5510,143550,zr2209
17,Turkey,Turkey,34,Male,Yes,Yes,Medium,25 to less than 50,25 to less than 50,999,...,NaN,NaN,NaN,NaN,9329,9996,1062,9996,118350,zr2209
18,Spain,Spain,60,Male,Yes,Yes,Medium,NaN,NaN,glg,...,Neither agree nor disagree,Disagree,NaN,NaN,9996,5412,9996,8423,150997,zr2209
19,United States,United States,NaN,Female,Yes,Yes,High,50 to less than 75,50 to less than 75,999,...,Strongly disagree,Agree,NaN,NaN,9999,9996,9999,9996,41077,zr2209
20,United States,United States,NaN,Male,Yes,Yes,Medium,10 to less than 25,10 to less than 25,999,...,Agree,Agree,NaN,NaN,9999,9996,9999,9996,193629,zr2209
21,United States,United States,NaN,Male,Yes,Yes,Medium,50 to less than 75,50 to less than 75,999,...,Strongly agree,Agree,NaN,NaN,9999,9996,9999,9996,62489,zr2209
22,United States,United States,NaN,Female,Yes,No,Medium,NaN,NaN,999,...,Agree,Disagree,NaN,NaN,9996,9996,9996,9996,77242,zr2209
23,United States,United States,NaN,Male,No,Yes,Low,NaN,NaN,999,...,Agree,Strongly agree,NaN,NaN,9996,9996,9996,9996,41662,zr2209
24,Japan,Japan,61,Female,Yes,Yes,Medium,NaN,NaN,jpn,...,Strongly agree,Strongly agree,NaN,NaN,9996,9996,9996,9996,74815,zr2209
25,Turkey,Turkey,20,Male,Yes,Yes,High,NaN,NaN,999,...,NaN,NaN,NaN,NaN,4110,9996,8430,4711,167650,zr2209
26,Italy,Italy,42,Female,Yes,Yes,Low,50 to less than 75,50 to less than 75,999,...,Strongly agree,Strongly agree,NaN,NaN,5321,9996,8610,9996,182530,zr2209
27,United Kingdom,England (UK),63,Female,Yes,No,Medium,NaN,NaN,eng,...,Strongly agree,Agree,NaN,NaN,9996,5322,9996,8730,13522,zr2209
28,United States,United States,NaN,Male,Yes,Yes,High,50 to less than 75,50 to less than 75,999,...,Neither agree nor disagree,Neither agree nor disagree,NaN,NaN,9999,9996,9999,9996,56559,zr2209
29,Spain,Spain,34,Male,Yes,Yes,Medium,NaN,NaN,spa,...,Agree,Strongly agree,NaN,NaN,9996,5221,9996,8030,36229,zr2209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19971,Korea,Korea,48,Male,Yes,Yes,Low,50 to less than 75,50 to less than 75,kor,...,Agree,Agree,NaN,NaN,5211,9996,4641,9996,141487,zr2209
19972,United States,United States,NaN,Male,Yes,Yes,Medium,75 to less than 90,75 to less than 90,999,...,Strongly agree,Disagree,NaN,NaN,9999,9996,9999,9996,162422,zr2209
19973,Chile,Chile,40,Male,Yes,Yes,Low,Less than 10,NaN,spa,...,Agree,Strongly agree,NaN,NaN,7522,9996,3100,9996,112918,zr2209
19974,Turkey,Turkey,26,Male,Yes,Yes,Low,10 to less than 25,10 to less than 25,999,...,NaN,NaN,NaN,NaN,3122,9996,4721,9996,135416,zr2209
19975,United States,United States,NaN,Female,No,Yes,Low,NaN,NaN,999,...,Strongly agree,Strongly agree,NaN,NaN,9996,9996,9996,9996,193023,zr2209
19976,Chile,Chile,51,Male,Yes,Yes,Medium,50 to less than 75,50 to less than 75,spa,...,Strongly agree,Strongly agree,NaN,NaN,5230,9996,8411,9996,62860,zr2209
19977,Spain,Spain,37,Female,Yes,Yes,High,NaN,NaN,spa,...,Disagree,Disagree,NaN,NaN,9996,4214,9996,4721,33826,zr2209
19978,United States,United States,NaN,Female,Yes,Yes,Low,NaN,NaN,999,...,Neither agree nor disagree,Neither agree nor disagree,NaN,NaN,9996,9999,9996,9999,150978,zr2209
19979,United States,United States,NaN,Female,Yes,Yes,High,NaN,NaN,999,...,Neither agree nor disagree,Agree,NaN,NaN,9999,9996,9999,9996,110276,zr2209
19980,Turkey,Turkey,31,Male,No,Yes,Low,10 to less than 25,10 to less than 25,999,...,NaN,NaN,NaN,NaN,5131,9996,5610,9996,84036,zr2209
19981,United States,United States,NaN,Female,Yes,Yes,Medium,75 to less than 90,75 to less than 90,999,...,Strongly disagree,Agree,NaN,NaN,9999,9996,9999,9996,178081,zr2209
19982,Canada,Canada (French),NaN,Female,Yes,Yes,Medium,50 to less than 75,50 to less than 75,999,...,Disagree,Disagree,NaN,NaN,9999,9996,9999,9999,97507,zr2209
19983,Spain,Spain,44,Male,Yes,Yes,Low,NaN,NaN,spa,...,Strongly agree,Strongly agree,NaN,NaN,9996,8332,9996,163,108360,zr2209
19984,Japan,Japan,16,Male,Yes,Yes,Low,NaN,NaN,jpn,...,Agree,Disagree,NaN,NaN,9996,9996,9996,9996,52219,zr2209
19985,Russian Federation,Russian Federation,27,Female,Yes,Yes,Medium,NaN,NaN,999,...,Disagree,Strongly agree,NaN,NaN,9996,9996,9996,9996,188735,zr2209
19986,Italy,Italy,63,Female,Yes,Yes,Low,NaN,NaN,999,...,Strongly agree,Strongly agree,NaN,NaN,9996,9996,9996,9996,79651,zr2209
19987,Poland,Poland,30,Female,Yes,Yes,High,90 or more,90 or more,pol,...,Agree,Agree,NaN,NaN,1120,9996,111,9996,158560,zr2209
19988,Poland,Poland,42,Female,Yes,Yes,High,NaN,NaN,pol,...,Strongly agree,Strongly agree,NaN,NaN,3334,9996,6820,9996,99106,zr2209
19989,France,France,18,Female,Yes,Yes,Medium,NaN,NaN,fra,...,Strongly agree,Strongly agree,NaN,NaN,9996,9996,9996,9996,172043,zr2209
19990,United States,United States,NaN,Female,Yes,Yes,Medium,NaN,NaN,999,...,Strongly agree,Strongly agree,NaN,NaN,9996,9999,9996,9999,92904,zr2209
19991,United States,United States,NaN,Female,No,Yes,Medium,25 to less than 50,25 to less than 50,999,...,Agree,Strongly agree,NaN,NaN,9999,9996,9999,9996,64379,zr2209
19992,Turkey,Turkey,39,Female,No,No,Low,NaN,NaN,999,...,NaN,NaN,NaN,NaN,9996,9996,9996,9996,107235,zr2209
19993,United States,United States,NaN,Female,Yes,No,Medium,NaN,NaN,999,...,Strongly agree,Strongly agree,NaN,NaN,9996,9999,9996,9999,177837,zr2209
19994,Italy,Italy,49,Male,Yes,Yes,High,90 or more,90 or more,999,...,Agree,Agree,NaN,NaN,5412,9996,8423,9996,33932,zr2209
19995,Israel,Israel,34,Female,Yes,Yes,High,50 to less than 75,50 to less than 75,heb,...,Disagree,Disagree,NaN,NaN,3352,9996,8430,9996,39799,zr2209
19996,Japan,Japan,35,Female,Yes,Yes,Medium,Less than 10,Less than 10,jpn,...,Strongly agree,Neither agree nor disagree,NaN,NaN,4110,9996,8810,9996,58503,zr2209
19997,Italy,Italy,17,Male,Yes,Yes,Low,NaN,NaN,999,...,Disagree,Agree,NaN,NaN,9996,9996,9996,9996,174555,zr2209
19998,Korea,Korea,19,Male,Yes,Yes,Medium,NaN,NaN,kor,...,Neither agree nor disagree,Agree,NaN,NaN,9996,9996,9996,9996,92498,zr2209
19999,Germany,Germany,NaN,Male,Yes,Yes,High,NaN,NaN,999,...,Strongly agree,Strongly agree,NaN,NaN,9999,9996,9999,9996,55223,zr2209
20000,United States,United States,NaN,Male,Yes,Yes,Low,NaN,NaN,999,...,Disagree,Agree,NaN,NaN,9999,9996,9999,9996,118940,zr2209

In [215]:
data = df.values
data_test = df_test.values

In [200]:
def is_number(s):
    try:  # 如果能运行float(s)语句，返回True（字符串s是浮点数）
        float(s)
        return True
    except ValueError:  # ValueError为Python的一种标准异常，表示"传入无效的参数"
        pass  # 如果引发了ValueError这种异常，不做任何事情（pass：不做任何事情，一般用做占位语句）
    try:
        import unicodedata  # 处理ASCii码的包
        unicodedata.numeric(s)  # 把一个表示数字的字符串转换为浮点数返回的函数
        return True
    except (TypeError, ValueError):
        pass
    return False

In [105]:
is_number('556.5624vd6576')

False

In [201]:
import numpy as np
import math
for i in range(0, 380):
    answer = set()
    is_num = True
    for j in range(1, 20001):
        if type(data[j][i]) == str:
#             print(type(data[j][i]),j,i)
            if not is_number(data[j][i]):
                is_num = False
                break
    print(is_num, i)
    if is_num == True:
        for j in range(1, 20001):
            if type(data[j][i]) != str:
                continue
            else:
                data[j][i] = float(data[j][i])
                
        for j in range(1, 20001):
            if type(data_test[j][i]) != str or i == 100:
                continue
            else:
                data_test[j][i] = float(data_test[j][i])
    else:
        for j in range(1, 20001):
            answer.add(data[j][i])
        f_to_num = {}
        n = 0
        for ans in answer:
            f_to_num[ans] = n
            n = n + 1
        for j in range(1, 20001):
            if type(data[j][i]) != str:
                continue
            else:
                data[j][i] = f_to_num[data[j][i]]
                
        for j in range(1, 20001):
            if type(data_test[j][i]) != str:
                continue
            elif data_test[j][i] in answer:
                data_test[j][i] = f_to_num[data_test[j][i]]
            else:
                data_test[j][i] = 0

False 0
False 1
True 2
False 3
False 4
False 5
False 6
False 7
False 8
False 9
False 10
False 11
False 12
False 13
False 14
True 15
True 16
True 17
False 18
False 19
False 20
False 21
False 22
True 23
False 24
False 25
False 26
False 27
False 28
False 29
False 30
False 31
False 32
True 33
False 34
False 35
False 36
False 37
False 38
False 39
False 40
False 41
False 42
True 43
True 44
True 45
False 46
False 47
False 48
False 49
False 50
False 51
False 52
True 53
True 54
True 55
True 56
True 57
True 58
True 59
True 60
True 61
True 62
True 63
True 64
True 65
True 66
True 67
False 68
False 69
False 70
False 71
False 72
False 73
False 74
False 75
False 76
False 77
True 78
False 79
True 80
False 81
True 82
False 83
True 84
False 85
True 86
False 87
True 88
False 89
True 90
False 91
True 92
False 93
True 94
False 95
True 96
False 97
True 98
False 99
True 100
False 101
False 102
False 103
False 104
False 105
True 106
False 107
True 108
True 109
False 110
True 111
False 112
False 113
False 114
False 115
False 116
False 117
False 118
False 119
False 120
False 121
True 122
False 123
True 124
False 125
True 126
False 127
False 128
True 129
True 130
False 131
False 132
False 133
False 134
False 135
False 136
False 137
False 138
False 139
False 140
True 141
False 142
True 143
True 144
False 145
True 146
True 147
False 148
True 149
True 150
False 151
False 152
False 153
False 154
False 155
False 156
False 157
False 158
False 159
True 160
True 161
True 162
False 163
False 164
False 165
False 166
False 167
False 168
False 169
False 170
False 171
False 172
False 173
False 174
False 175
False 176
False 177
False 178
False 179
False 180
False 181
False 182
True 183
False 184
False 185
False 186
False 187
False 188
False 189
False 190
False 191
False 192
False 193
False 194
False 195
False 196
False 197
False 198
False 199
False 200
False 201
False 202
True 203
False 204
True 205
False 206
True 207
True 208
False 209
False 210
True 211
True 212
False 213
False 214
False 215
False 216
True 217
False 218
True 219
False 220
True 221
False 222
True 223
False 224
False 225
False 226
False 227
False 228
False 229
False 230
False 231
False 232
False 233
True 234
True 235
True 236
False 237
False 238
False 239
False 240
False 241
False 242
False 243
False 244
False 245
False 246
False 247
False 248
False 249
True 250
True 251
True 252
True 253
False 254
False 255
False 256
False 257
False 258
False 259
False 260
False 261
True 262
False 263
False 264
True 265
False 266
False 267
False 268
False 269
False 270
False 271
True 272
False 273
True 274
True 275
False 276
True 277
False 278
False 279
False 280
False 281
True 282
True 283
False 284
False 285
False 286
False 287
False 288
False 289
False 290
False 291
False 292
False 293
False 294
False 295
False 296
False 297
False 298
False 299
False 300
False 301
False 302
False 303
False 304
False 305
False 306
False 307
False 308
False 309
False 310
False 311
False 312
False 313
False 314
False 315
False 316
False 317
False 318
False 319
False 320
False 321
False 322
False 323
False 324
False 325
False 326
False 327
False 328
False 329
False 330
False 331
False 332
False 333
False 334
False 335
False 336
False 337
False 338
False 339
False 340
False 341
False 342
False 343
False 344
False 345
False 346
False 347
False 348
False 349
False 350
False 351
False 352
False 353
False 354
False 355
False 356
False 357
False 358
False 359
False 360
False 361
False 362
False 363
False 364
False 365
False 366
False 367
False 368
False 369
False 370
False 371
False 372
False 373
True 374
True 375
False 376
True 377
True 378
False 379

In [41]:
df.iloc[3][1]

'Japan'

In [112]:
data

array([['cntryid', 'cntryid_e', 'age_r', ..., 'v105', 'row', 'uni'],
       [3, 5, nan, ..., 9996.0, 29198.0, 0],
       [9, 11, 58.0, ..., 9996.0, 59475.0, 0],
       ...,
       [9, 11, 48.0, ..., 9996, 78714, 0],
       [28, 30, nan, ..., 9996, 94816, 0],
       [2, 4, 48.0, ..., 9996, 62678, 0]], dtype=object)

In [14]:
df.loc[:,100]

0         job_performance
1        1923.97352845319
2        3235.50983682381
3        3191.92064867994
4        2926.99829631408
5        2755.81213153805
6        3055.37756976248
7        3150.74244382012
8        3522.98909669229
9          2459.384156874
10       3028.30751835672
11       3494.68225241624
12       2646.98684560466
13       2697.83456988028
14       3229.59163942512
15       2649.51938877813
16       3286.28271244504
17       3078.40948440561
18       3253.00597808618
19       1939.40753129898
20       3309.26918434392
21        2982.5198929787
22       3057.68166895529
23       3487.30340850703
24       2919.64875367113
25       2256.10040566706
26       3000.94498510368
27        1835.6333778079
28       3742.62904551453
29       2761.19659159199
               ...
19971             2234.12
19972             3276.07
19973             3019.06
19974             2143.75
19975             2818.21
19976             2587.99
19977             2678.98
19978             3193.98
19979             2463.89
19980             2741.34
19981             2714.83
19982             1836.31
19983              2315.2
19984             2289.49
19985              2832.1
19986             3251.07
19987             3012.65
19988             2969.14
19989             2874.76
19990             3116.58
19991             2033.44
19992             2770.71
19993             3020.85
19994             3286.39
19995             3044.65
19996             3199.74
19997             3607.78
19998             3292.25
19999             3799.66
20000             2797.49
Name: 100, Length: 20001, dtype: object

In [225]:
from sklearn.model_selection import train_test_split
data[pd.isnull(data)] = 0
data_non = data
y = data_non[1:20001,100]
x = np.concatenate((data_non[1:20001,0:100],data_non[1:20001,101:380]),axis = 1)
scaler = StandardScaler() # 标准化转换
scaler.fit(x)  # 训练标准化对象
X = scaler.transform(x)   # 转换数据集
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = .1, random_state = 0)

In [52]:
# from sklearn.neural_network import MLPRegressor  # 多层线性回归
# from sklearn.preprocessing import StandardScaler

# scaler = StandardScaler() # 标准化转换
# scaler.fit(x)  # 训练标准化对象
# X = scaler.transform(x)   # 转换数据集

# clf = MLPRegressor(solver='adam', alpha=1e-5,hidden_layer_sizes=(400,400,400,400), shuffle=True, random_state=7)
# clf.fit(X, y)

MLPRegressor(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(400, 400, 400, 400), learning_rate='constant',
             learning_rate_init=0.001, max_iter=200, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=7, shuffle=True, solver='adam', tol=0.0001,
             validation_fraction=0.1, verbose=False, warm_start=False)

In [53]:
# scaler.fit(x_test)  # 训练标准化对象
# X_test = scaler.transform(x_test)
# y_pred = clf.predict(X_test)

In [54]:
# loss = 0
# for i in range(0, len(y_test)):
#     loss = loss + (y_pred[i] - y_test[i]) * (y_pred[i] - y_test[i])

In [55]:
# loss = loss / len(y_test)

In [56]:
# loss

3122003.862088242

In [203]:
# y = data_non[1:18000,100]
# x = np.concatenate((data_non[1:18000,0:100],data_non[1:18000,101:380]),axis = 1)
# y_test = data_non[18001:20001,100]
# x_test = np.concatenate((data_non[18001:20001,0:100],data_non[18001:20001,101:380]),axis = 1)
scaler = StandardScaler() # 标准化转换
scaler.fit(x)  # 训练标准化对象
X = scaler.transform(x)   # 转换数据集

In [226]:
#加激活函数的方法1：mode.add(Activation(''))
from keras.optimizers import Adam
from keras.layers import Dense,Activation
from keras.models import Sequential

#构建一个顺序模型
model=Sequential()

#在模型中添加一个全连接层
#units是输出维度,input_dim是输入维度(shift+两次tab查看函数参数)
model.add(Dense(units=256,input_dim=379))
model.add(Activation('relu'))
model.add(Dense(units=128))
model.add(Activation('relu'))
model.add(Dense(units=64))
model.add(Activation('relu'))
model.add(Dense(units=32))
model.add(Activation('relu'))
model.add(Dense(units=16))
model.add(Activation('relu'))
model.add(Dense(units=1))
# model.add(Activation('linear'))

#定义优化算法(修改学习率)
# defsgd=SGD(lr=0.003)
adam = Adam(lr=0.003, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)

#编译模型
model.compile(optimizer=adam,loss='mse')   #optimizer参数设置优化器,loss设置目标函数

#训练模型
model.fit(X_train, y_train, batch_size = 4, epochs = 30, validation_data = (X_val, y_val), verbose = 1, shuffle=True)

Train on 18000 samples, validate on 2000 samples
Epoch 1/30
18000/18000 [==============================] - 10s 560us/step - loss: 260814.1443 - val_loss: 97077.3943
Epoch 2/30
18000/18000 [==============================] - 9s 505us/step - loss: 109211.5621 - val_loss: 83532.7154
Epoch 3/30
18000/18000 [==============================] - 9s 507us/step - loss: 91584.2226 - val_loss: 80111.6464
Epoch 4/30
18000/18000 [==============================] - 9s 508us/step - loss: 73677.9335 - val_loss: 67010.2724
Epoch 5/30
18000/18000 [==============================] - 9s 520us/step - loss: 64147.2955 - val_loss: 66826.1269
Epoch 6/30
18000/18000 [==============================] - 10s 531us/step - loss: 56239.8397 - val_loss: 59948.9946
Epoch 7/30
18000/18000 [==============================] - 10s 540us/step - loss: 51219.8806 - val_loss: 63056.1538
Epoch 8/30
18000/18000 [==============================] - 10s 541us/step - loss: 42102.9441 - val_loss: 66546.4839
Epoch 9/30
18000/18000 [==============================] - 10s 542us/step - loss: 38886.6174 - val_loss: 50772.4588
Epoch 10/30
18000/18000 [==============================] - 10s 541us/step - loss: 32002.8510 - val_loss: 43445.4687
Epoch 11/30
18000/18000 [==============================] - 10s 552us/step - loss: 38183.7082 - val_loss: 44923.0769
Epoch 12/30
18000/18000 [==============================] - 10s 583us/step - loss: 25329.4848 - val_loss: 41842.2295
Epoch 13/30
18000/18000 [==============================] - 10s 580us/step - loss: 22909.9222 - val_loss: 38190.8280
Epoch 14/30
18000/18000 [==============================] - 11s 588us/step - loss: 20537.3798 - val_loss: 43971.9686
Epoch 15/30
18000/18000 [==============================] - 10s 543us/step - loss: 18638.7628 - val_loss: 36694.1838
Epoch 16/30
18000/18000 [==============================] - 10s 542us/step - loss: 19450.5512 - val_loss: 40812.7642
Epoch 17/30
18000/18000 [==============================] - 10s 544us/step - loss: 16941.6425 - val_loss: 43484.7717
Epoch 18/30
18000/18000 [==============================] - 10s 544us/step - loss: 14324.2941 - val_loss: 36907.7682
Epoch 19/30
18000/18000 [==============================] - 10s 549us/step - loss: 13550.3757 - val_loss: 35229.5407
Epoch 20/30
18000/18000 [==============================] - 10s 546us/step - loss: 12404.0834 - val_loss: 36584.0888
Epoch 21/30
18000/18000 [==============================] - 10s 555us/step - loss: 11909.5087 - val_loss: 36659.9365
Epoch 22/30
18000/18000 [==============================] - 10s 536us/step - loss: 10392.4694 - val_loss: 33953.8315
Epoch 23/30
18000/18000 [==============================] - 10s 541us/step - loss: 9320.3686 - val_loss: 33268.6348
Epoch 24/30
18000/18000 [==============================] - 10s 542us/step - loss: 9886.2916 - val_loss: 48003.3802
Epoch 25/30
18000/18000 [==============================] - 10s 539us/step - loss: 8857.4078 - val_loss: 33122.8584
Epoch 26/30
18000/18000 [==============================] - 10s 539us/step - loss: 9410.9417 - val_loss: 35675.4992
Epoch 27/30
18000/18000 [==============================] - 10s 542us/step - loss: 7839.9560 - val_loss: 35631.1867
Epoch 28/30
18000/18000 [==============================] - 10s 546us/step - loss: 7633.1589 - val_loss: 36850.8646
Epoch 29/30
18000/18000 [==============================] - 10s 546us/step - loss: 7724.2230 - val_loss: 34546.3015
Epoch 30/30
18000/18000 [==============================] - 10s 546us/step - loss: 10329.1707 - val_loss: 32464.1774

In [205]:
scaler.fit(x_test)  # 训练标准化对象
X_test = scaler.transform(x_test)   # 转换数据集
y_pred = model.predict(X_test)
loss = 0
for i in range(0, len(y_test)):
    loss = loss + (y_pred[i] - y_test[i]) * (y_pred[i] - y_test[i])
loss = loss / len(y_test)
print(loss)

[39545.152]

In [227]:
data_test[pd.isnull(data_test)] = 0
x_te = np.concatenate((data_test[1:20001,0:100],data_test[1:20001,101:380]),axis = 1)
scaler.fit(x_te)  # 训练标准化对象
X_te = scaler.transform(x_te)   # 转换数据集
y_tepred = model.predict(X_te)
df_test = pd.read_csv('hw5-testset-zr2209.csv', sep=',',header=None)
data_out = df_test.values

/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (2,15,16,17,23,33,43,44,45,50,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,78,80,82,84,86,88,90,92,94,96,98,100,106,108,109,111,122,124,126,129,130,141,143,144,146,147,149,150,160,161,162,183,203,205,207,208,211,212,217,219,221,223,234,235,236,250,251,252,253,255,256,257,258,260,262,265,268,272,274,275,277,280,282,283,374,375,376,377,378) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [228]:
for i in range(0, len(y_tepred)):
    data_out[i+1,100] = y_tepred[i][0]

In [235]:
data_out[:,100]

array(['job_performance', 1402.6216, 4089.23, ..., 2471.6184, 2661.89,
       2194.235], dtype=object)

In [237]:
data_out

array([['cntryid', 'cntryid_e', 'age_r', ..., 'v105', 'row', 'uni'],
       ['Turkey', 'Turkey', '22', ..., '9996', '188703', 'zr2209'],
       ['France', 'France', '38', ..., '9996', '21130', 'zr2209'],
       ...,
       ['Korea', 'Korea', 19.0, ..., 9996, 92498, 'zr2209'],
       ['Germany', 'Germany', nan, ..., 9996, 55223, 'zr2209'],
       ['United States', 'United States', nan, ..., 9996, 118940,
        'zr2209']], dtype=object)

In [247]:
dff = pd.DataFrame(data_out)
dff.to_csv('hw5-testset-zr2209-submission.csv',index=0,header=0)

In [248]:
dfff=pd.read_csv('hw5-testset-zr2209-submission.csv', sep=',',header=None)

In [249]:
dfff

,0,1,2,3,4,5,6,7,8,9,...,370,371,372,373,374,375,376,377,378,379
0,cntryid,cntryid_e,age_r,gender_r,computerexperience,nativespeaker,edlevel3,monthlyincpr,yearlyincpr,lng_home,...,v85,v50,v89,v127,v239,v224,v71,v105,row,uni
1,Turkey,Turkey,22,Female,Yes,Yes,Low,NaN,NaN,999,...,NaN,NaN,NaN,NaN,9996,9996,9996,9996,188703,zr2209
2,France,France,38,Male,Yes,Yes,Medium,25 to less than 50,50 to less than 75,fra,...,Strongly agree,Strongly agree,NaN,NaN,3123,9996,4312,9996,21130,zr2209
3,Turkey,Turkey,19,Male,Yes,Yes,Medium,NaN,NaN,999,...,NaN,NaN,NaN,NaN,9996,9996,9996,9996,110731,zr2209
4,Japan,Japan,42,Female,Yes,Yes,Medium,Less than 10,Less than 10,jpn,...,Strongly disagree,Agree,NaN,NaN,4212,9996,9200,9996,39944,zr2209
5,Japan,Japan,27,Male,Yes,Yes,High,25 to less than 50,25 to less than 50,jpn,...,Strongly agree,Agree,NaN,NaN,3339,9996,6312,9996,15584,zr2209
6,Japan,Japan,61,Male,Yes,Yes,High,90 or more,90 or more,jpn,...,Agree,Disagree,NaN,NaN,3134,9996,1920,9996,8986,zr2209
7,United Kingdom,England (UK),55,Female,Yes,Yes,High,Less than 10,Less than 10,eng,...,Disagree,Disagree,NaN,NaN,431,9996,8620,9996,188269,zr2209
8,Israel,Israel,19,Female,Yes,Yes,Medium,Less than 10,Less than 10,ara,...,Disagree,Strongly agree,NaN,NaN,5223,9996,4721,9996,127184,zr2209
9,Greece,Greece,62,Male,Yes,Yes,Medium,NaN,NaN,ell,...,Strongly agree,Strongly agree,NaN,NaN,9996,9996,9996,9996,103553,zr2209
10,Poland,Poland,30,Female,Yes,Yes,High,50 to less than 75,50 to less than 75,pol,...,Agree,Agree,NaN,NaN,2310,9996,8530,9996,95830,zr2209
11,Belgium,Flanders (Belgium),56,Male,Yes,Yes,Medium,50 to less than 75,50 to less than 75,nld,...,Neither agree nor disagree,Disagree,NaN,NaN,9622,9996,5310,9996,175973,zr2209
12,Turkey,Turkey,24,Male,Yes,Yes,High,Less than 10,NaN,999,...,NaN,NaN,NaN,NaN,3431,9996,7420,9996,36639,zr2209
13,Poland,Poland,37,Male,Yes,Yes,Medium,10 to less than 25,10 to less than 25,pol,...,Agree,Agree,NaN,NaN,8131,9996,3290,9996,130932,zr2209
14,Turkey,Turkey,32,Female,Yes,Yes,Low,NaN,NaN,999,...,NaN,NaN,NaN,NaN,9996,9996,9996,9996,31490,zr2209
15,Germany,Germany,NaN,Female,Yes,Yes,Low,NaN,NaN,999,...,Agree,Neither agree nor disagree,NaN,NaN,9996,9996,9996,9996,31525,zr2209
16,Italy,Italy,21,Male,Yes,Yes,Medium,NaN,NaN,999,...,Agree,Agree,NaN,NaN,9996,5131,9996,5510,143550,zr2209
17,Turkey,Turkey,34,Male,Yes,Yes,Medium,25 to less than 50,25 to less than 50,999,...,NaN,NaN,NaN,NaN,9329,9996,1062,9996,118350,zr2209
18,Spain,Spain,60,Male,Yes,Yes,Medium,NaN,NaN,glg,...,Neither agree nor disagree,Disagree,NaN,NaN,9996,5412,9996,8423,150997,zr2209
19,United States,United States,NaN,Female,Yes,Yes,High,50 to less than 75,50 to less than 75,999,...,Strongly disagree,Agree,NaN,NaN,9999,9996,9999,9996,41077,zr2209
20,United States,United States,NaN,Male,Yes,Yes,Medium,10 to less than 25,10 to less than 25,999,...,Agree,Agree,NaN,NaN,9999,9996,9999,9996,193629,zr2209
21,United States,United States,NaN,Male,Yes,Yes,Medium,50 to less than 75,50 to less than 75,999,...,Strongly agree,Agree,NaN,NaN,9999,9996,9999,9996,62489,zr2209
22,United States,United States,NaN,Female,Yes,No,Medium,NaN,NaN,999,...,Agree,Disagree,NaN,NaN,9996,9996,9996,9996,77242,zr2209
23,United States,United States,NaN,Male,No,Yes,Low,NaN,NaN,999,...,Agree,Strongly agree,NaN,NaN,9996,9996,9996,9996,41662,zr2209
24,Japan,Japan,61,Female,Yes,Yes,Medium,NaN,NaN,jpn,...,Strongly agree,Strongly agree,NaN,NaN,9996,9996,9996,9996,74815,zr2209
25,Turkey,Turkey,20,Male,Yes,Yes,High,NaN,NaN,999,...,NaN,NaN,NaN,NaN,4110,9996,8430,4711,167650,zr2209
26,Italy,Italy,42,Female,Yes,Yes,Low,50 to less than 75,50 to less than 75,999,...,Strongly agree,Strongly agree,NaN,NaN,5321,9996,8610,9996,182530,zr2209
27,United Kingdom,England (UK),63,Female,Yes,No,Medium,NaN,NaN,eng,...,Strongly agree,Agree,NaN,NaN,9996,5322,9996,8730,13522,zr2209
28,United States,United States,NaN,Male,Yes,Yes,High,50 to less than 75,50 to less than 75,999,...,Neither agree nor disagree,Neither agree nor disagree,NaN,NaN,9999,9996,9999,9996,56559,zr2209
29,Spain,Spain,34,Male,Yes,Yes,Medium,NaN,NaN,spa,...,Agree,Strongly agree,NaN,NaN,9996,5221,9996,8030,36229,zr2209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19971,Korea,Korea,48,Male,Yes,Yes,Low,50 to less than 75,50 to less than 75,kor,...,Agree,Agree,NaN,NaN,5211,9996,4641,9996,141487,zr2209
19972,United States,United States,NaN,Male,Yes,Yes,Medium,75 to less than 90,75 to less than 90,999,...,Strongly agree,Disagree,NaN,NaN,9999,9996,9999,9996,162422,zr2209
19973,Chile,Chile,40,Male,Yes,Yes,Low,Less than 10,NaN,spa,...,Agree,Strongly agree,NaN,NaN,7522,9996,3100,9996,112918,zr2209
19974,Turkey,Turkey,26,Male,Yes,Yes,Low,10 to less than 25,10 to less than 25,999,...,NaN,NaN,NaN,NaN,3122,9996,4721,9996,135416,zr2209
19975,United States,United States,NaN,Female,No,Yes,Low,NaN,NaN,999,...,Strongly agree,Strongly agree,NaN,NaN,9996,9996,9996,9996,193023,zr2209
19976,Chile,Chile,51,Male,Yes,Yes,Medium,50 to less than 75,50 to less than 75,spa,...,Strongly agree,Strongly agree,NaN,NaN,5230,9996,8411,9996,62860,zr2209
19977,Spain,Spain,37,Female,Yes,Yes,High,NaN,NaN,spa,...,Disagree,Disagree,NaN,NaN,9996,4214,9996,4721,33826,zr2209
19978,United States,United States,NaN,Female,Yes,Yes,Low,NaN,NaN,999,...,Neither agree nor disagree,Neither agree nor disagree,NaN,NaN,9996,9999,9996,9999,150978,zr2209
19979,United States,United States,NaN,Female,Yes,Yes,High,NaN,NaN,999,...,Neither agree nor disagree,Agree,NaN,NaN,9999,9996,9999,9996,110276,zr2209
19980,Turkey,Turkey,31,Male,No,Yes,Low,10 to less than 25,10 to less than 25,999,...,NaN,NaN,NaN,NaN,5131,9996,5610,9996,84036,zr2209
19981,United States,United States,NaN,Female,Yes,Yes,Medium,75 to less than 90,75 to less than 90,999,...,Strongly disagree,Agree,NaN,NaN,9999,9996,9999,9996,178081,zr2209
19982,Canada,Canada (French),NaN,Female,Yes,Yes,Medium,50 to less than 75,50 to less than 75,999,...,Disagree,Disagree,NaN,NaN,9999,9996,9999,9999,97507,zr2209
19983,Spain,Spain,44,Male,Yes,Yes,Low,NaN,NaN,spa,...,Strongly agree,Strongly agree,NaN,NaN,9996,8332,9996,163,108360,zr2209
19984,Japan,Japan,16,Male,Yes,Yes,Low,NaN,NaN,jpn,...,Agree,Disagree,NaN,NaN,9996,9996,9996,9996,52219,zr2209
19985,Russian Federation,Russian Federation,27,Female,Yes,Yes,Medium,NaN,NaN,999,...,Disagree,Strongly agree,NaN,NaN,9996,9996,9996,9996,188735,zr2209
19986,Italy,Italy,63,Female,Yes,Yes,Low,NaN,NaN,999,...,Strongly agree,Strongly agree,NaN,NaN,9996,9996,9996,9996,79651,zr2209
19987,Poland,Poland,30,Female,Yes,Yes,High,90 or more,90 or more,pol,...,Agree,Agree,NaN,NaN,1120,9996,111,9996,158560,zr2209
19988,Poland,Poland,42,Female,Yes,Yes,High,NaN,NaN,pol,...,Strongly agree,Strongly agree,NaN,NaN,3334,9996,6820,9996,99106,zr2209
19989,France,France,18,Female,Yes,Yes,Medium,NaN,NaN,fra,...,Strongly agree,Strongly agree,NaN,NaN,9996,9996,9996,9996,172043,zr2209
19990,United States,United States,NaN,Female,Yes,Yes,Medium,NaN,NaN,999,...,Strongly agree,Strongly agree,NaN,NaN,9996,9999,9996,9999,92904,zr2209
19991,United States,United States,NaN,Female,No,Yes,Medium,25 to less than 50,25 to less than 50,999,...,Agree,Strongly agree,NaN,NaN,9999,9996,9999,9996,64379,zr2209
19992,Turkey,Turkey,39,Female,No,No,Low,NaN,NaN,999,...,NaN,NaN,NaN,NaN,9996,9996,9996,9996,107235,zr2209
19993,United States,United States,NaN,Female,Yes,No,Medium,NaN,NaN,999,...,Strongly agree,Strongly agree,NaN,NaN,9996,9999,9996,9999,177837,zr2209
19994,Italy,Italy,49,Male,Yes,Yes,High,90 or more,90 or more,999,...,Agree,Agree,NaN,NaN,5412,9996,8423,9996,33932,zr2209
19995,Israel,Israel,34,Female,Yes,Yes,High,50 to less than 75,50 to less than 75,heb,...,Disagree,Disagree,NaN,NaN,3352,9996,8430,9996,39799,zr2209
19996,Japan,Japan,35,Female,Yes,Yes,Medium,Less than 10,Less than 10,jpn,...,Strongly agree,Neither agree nor disagree,NaN,NaN,4110,9996,8810,9996,58503,zr2209
19997,Italy,Italy,17,Male,Yes,Yes,Low,NaN,NaN,999,...,Disagree,Agree,NaN,NaN,9996,9996,9996,9996,174555,zr2209
19998,Korea,Korea,19,Male,Yes,Yes,Medium,NaN,NaN,kor,...,Neither agree nor disagree,Agree,NaN,NaN,9996,9996,9996,9996,92498,zr2209
19999,Germany,Germany,NaN,Male,Yes,Yes,High,NaN,NaN,999,...,Strongly agree,Strongly agree,NaN,NaN,9999,9996,9999,9996,55223,zr2209
20000,United States,United States,NaN,Male,Yes,Yes,Low,NaN,NaN,999,...,Disagree,Agree,NaN,NaN,9999,9996,9999,9996,118940,zr2209

In [242]:
data[20000,378]

62678

In [131]:
df.loc[20000,378]

62678

In [246]:
data_out

array([['cntryid', 'cntryid_e', 'age_r', ..., 'v105', 'row', 'uni'],
       ['Turkey', 'Turkey', '22', ..., '9996', '188703', 'zr2209'],
       ['France', 'France', '38', ..., '9996', '21130', 'zr2209'],
       ...,
       ['Korea', 'Korea', 19.0, ..., 9996, 92498, 'zr2209'],
       ['Germany', 'Germany', nan, ..., 9996, 55223, 'zr2209'],
       ['United States', 'United States', nan, ..., 9996, 118940,
        'zr2209']], dtype=object)